### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by Jannik-Schroeder** [solun-pm/solun-auth#1]
Authentication:
Login -> Solun Auth Server -> Erfolgreicher Login
Speicherung in DB mit Login-Token, sendet Anfrage zu mail.solun.pm/auth/<token>

if token correct, delete token from databse for user and login user with jwt-token cookie in webmail application

**Comment by DanielWTE** [comment]
![Solun Auth](https://github.com/solun-pm/solun-auth/assets/69986202/03e6269d-552c-487f-a915-6c018c250f6d)
